stages : 
  - notify 
  - install-dependencies # if you do lint , test files on local use it here 
  - lint
  - test
  - build-docker-images
  - deploy

variables:
  PLACEHOLDER_DIRECTORY: placeholder
  FRONT_SERVICE_TAG_LATEST: $DOCKERHUB_USERNAME/react-service:latest
  BACK_SERVICE_TAG_LATEST: $DOCKERHUB_USERNAME/flask-service:latest
  PLACEHOLDER_LATEST: placeholder
  # REACT_APP_API_URL_ARG: "" # NOT AFFECT THE BUILD OF FLASK
  BASE_IMAGE: "" # can be node:18-alpine or python:3.11
  COMMAND: "" # can be npm install or python -m venv ./youssef/venv ,...etc
  ARTIFACT_PATH: "" # can be ./frontend/node_modules or ./backend/youssef/venv




slack_pipeline_start:
  stage: notify
  image: curlimages/curl:latest
  script:
    - >
      curl -X POST -H "Content-type: application/json" --data "{
        \"text\": \"👋 Hello team! Pipeline *#${CI_PIPELINE_ID}* just started on branch *${CI_COMMIT_REF_NAME}*! 🛠️\n\n🥁 *Drum rolls...* Get ready for action! 💪\n\n🎉 Let's hope this one doesn't break prod 😅\n\n🔗 <${CI_PIPELINE_URL}|Click here to watch the show!>\"
      }" $SLACK_WEBHOOK_URL


# want cache if you will do lint ,test to preserve the dependencies not install each time also cache ansible in last job not every deployment install it again 
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ./frontend/node_modules
    - ./backend/youssef/venv


.install-dependencies-template:
  stage: install-dependencies
  image: $BASE_IMAGE
  script:
    - cd $PLACEHOLDER_DIRECTORY
    - $COMMAND
  artifacts:
    paths:
      - $ARTIFACT_PATH
  needs:
    - slack_pipeline_start
    
install-dependencies-front:
  extends: .install-dependencies-template
  variables:
    BASE_IMAGE: node:18-alpine
    PLACEHOLDER_DIRECTORY: ./frontend
    COMMAND: npm install
    ARTIFACT_PATH: ./frontend/node_modules


install-dependencies-back:
  extends: .install-dependencies-template
  variables:
    BASE_IMAGE: python:3.11
    PLACEHOLDER_DIRECTORY: ./backend
    # COMMAND: sh -c 'python -m venv ./youssef/venv && . ./youssef/venv/bin/activate && pip install --no-cache-dir -r requirements.txt' # the venv created inside backend dir beside files of app
    ARTIFACT_PATH: ./backend/youssef/venv
  #the command cause error so i will implement it here 
  script: # its like i made antoher script section beside the extended one 
    - cd $PLACEHOLDER_DIRECTORY
    - python -m venv ./youssef/venv
    - . ./youssef/venv/bin/activate
    - pip install --no-cache-dir -r requirements.txt

.lint-template:
  stage: lint
  image: $BASE_IMAGE
  script:
    - cd $PLACEHOLDER_DIRECTORY
    - $COMMAND


lint-front:
  extends: .lint-template
  variables:
    BASE_IMAGE: node:18-alpine
    PLACEHOLDER_DIRECTORY: ./frontend
    COMMAND: npm run lint 
  needs:
    - install-dependencies-front

lint-back:
  extends: .lint-template
  variables:
    BASE_IMAGE: python:3.11
    PLACEHOLDER_DIRECTORY: ./backend
    # need to activate venv before run flake8
    # COMMAND: flake8
  script:
    - cd $PLACEHOLDER_DIRECTORY
    - . ./youssef/venv/bin/activate
    - flake8 app.py 
  needs:
    - install-dependencies-back


.test-template:
  stage: test
  image: $BASE_IMAGE
  script:
    - cd $PLACEHOLDER_DIRECTORY
    - $COMMAND

test-front:
  extends: .test-template
  variables:
    BASE_IMAGE: node:18-alpine
    PLACEHOLDER_DIRECTORY: ./frontend
    COMMAND: npm run test
  needs:
    - lint-front

test-back:
  extends: .test-template
  variables:
    BASE_IMAGE: python:3.11
    PLACEHOLDER_DIRECTORY: ./backend
    # need to activate venv before run pytest
    # COMMAND: pytest
  script:
    - cd $PLACEHOLDER_DIRECTORY
    - . ./youssef/venv/bin/activate
    - pytest test_app.py || true
  needs:
    - lint-back



.dockerize_template:
  stage: build-docker-images
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
  script:
    - cd $PLACEHOLDER_DIRECTORY
    - docker build ${REACT_APP_API_URL_ARG} -t  app:v1 .
    - docker tag app:v1 $PLACEHOLDER_LATEST
    - docker push $PLACEHOLDER_LATEST

dockarize-react:
  extends: .dockerize_template
  variables:
    PLACEHOLDER_DIRECTORY: frontend
    PLACEHOLDER_LATEST: $FRONT_SERVICE_TAG_LATEST
    # REACT_APP_API_URL_ARG: --build-arg REACT_APP_API_URL=http://$EC2_HOST/api   # this replace http//localhost:3000/api in front 
    REACT_APP_API_URL_ARG: --build-arg REACT_APP_API_URL=https://$EC2_HOST/api   # cause its will be static in code and you can do APIURL='/api' on ly in code and it work but because he put the ip static in code and this not normal so i will but here in var as https  

  needs:
    - test-front

dockarize-flask:
  extends: .dockerize_template
  variables:
    PLACEHOLDER_DIRECTORY: backend
    PLACEHOLDER_LATEST: $BACK_SERVICE_TAG_LATEST
  needs:
    - test-back



deploy_to_ec2:
  stage: deploy
  image: python:3.12 
  before_script:
  # install ssh client
    - apt-get update && apt-get install -y openssh-client
  # install ansible
    - pip install ansible==8.6.0
  # setup ssh
    # - eval $(ssh-agent -s)
    # - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - # autmate provide the .pem instead of provide throw command -i .pem =>  no need for those cause  its not real ssh i give ssh-private key to ansible when run the playbook --private-key=.pem
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts # instead of asking me first time to put the ip in known_hosts i put the ip $ec2_host
    - chmod 644 ~/.ssh/known_hosts
  script:
    # - ssh -o StrictHostKeyChecking=accept-new $EC2_USER@$EC2_HOST "sudo apt-get update -y && sudo apt-get install docker.io -y" # done inside ansible 
    # - ssh -o StrictHostKeyChecking=accept-new $EC2_USER@$EC2_HOST "sudo systemctl start docker" # done inside ansible
    # - ssh -o StrictHostKeyChecking=accept-new $EC2_USER@$EC2_HOST "sudo usermod -aG docker $EC2_USER" # ansible done implicitly
    # - ssh -o StrictHostKeyChecking=accept-new $EC2_USER@$EC2_HOST "newgrp docker" # ansible done implicitly
    # - ssh -o StrictHostKeyChecking=accept-new $EC2_USER@$EC2_HOST "docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD" # done with ansible
    # - ssh -o StrictHostKeyChecking=accept-new $EC2_USER@$EC2_HOST "docker pull $DOCKER_IMAGE_LATEST" # done with ansible
    # - ssh -o StrictHostKeyChecking=accept-new $EC2_USER@$EC2_HOST "docker stop $CI_JOB_NAME || true"
    # - ssh -o StrictHostKeyChecking=accept-new $EC2_USER@$EC2_HOST "docker rm $CI_JOB_NAME || true"
    # - ssh -o StrictHostKeyChecking=accept-new $EC2_USER@$EC2_HOST "docker run -d --name $CI_JOB_NAME -p $PORT:$PORT $DOCKER_IMAGE_LATEST"
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/private-key-file
  - chmod 600 ~/private-key-file
  - ansible-playbook -i $EC2_HOST, -u $EC2_USER --private-key=~/private-key-file playbook.yml --vault-password-file=<(echo $VAULT_PASSWORD)

  needs:
    - dockarize-react
    - dockarize-flask

